name: wine

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  DEBIAN_FRONTEND: noninteractive
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  ubuntu-18_04:
    runs-on: ubuntu-18.04
    env:
      WINECC: winegcc-stable
      WINEDEBUG: "-all"
    steps:
      - uses: actions/checkout@v2
      - name: Set up dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qq
          sudo apt-get install -yq g++-multilib pkg-config wine-stable wine64-tools
          sudo apt-get install -yq binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 mingw-w64
      #- name: make wine32
        #run: make wine32 -j $(nproc)
      - name: make wine64
        run: make wine64 -j $(nproc)
      - name: make win32 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++
        run: make win32 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ -j $(nproc)
      - name: make win64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
        run: make win64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ -j $(nproc)
      - name: make plugin-wine
        run: make plugin-wine -j $(nproc)
      - name: make plugin-wine CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
        run: make plugin-wine CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ -j $(nproc)

  ubuntu-20_04:
    runs-on: ubuntu-20.04
    env:
      WINECC: winegcc-stable
      WINEDEBUG: "-all"
    steps:
      - uses: actions/checkout@v2
      - name: Set up dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qq
          sudo apt-get install -yq g++-multilib pkg-config wine-stable wine64-tools
          sudo apt-get install -yq binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 mingw-w64
      #- name: make wine32
        #run: make wine32 -j $(nproc)
      - name: make wine64
        run: make wine64 -j $(nproc)
      - name: make win32 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++
        run: make win32 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ -j $(nproc)
      - name: make win64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
        run: make win64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ -j $(nproc)
      - name: make plugin-wine
        run: make plugin-wine -j $(nproc)
      - name: make plugin-wine CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++
        run: make plugin-wine CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ -j $(nproc)
